### PR TITLE
Initial Commit for hkdm systemd unit

### PR DESCRIPTION
**Pull request by DataEraserC**
Try this

### CODE REVIEW

**Comment by DataEraserC** [comment]
test required

**Comment by DataEraserC** [comment]
@gmicroul have u test it? I do not have any mobile-nixos supported devices

**Comment by gmicroul** [comment]
> @gmicroul have u test it? I do not have any mobile-nixos supported devices

[alice@nixos:~/mobile-nixos]$ nix-build examples/hkdm/ --argstr device oneplus-fajita -A outputs.android-fastboot-images
trace: (Using pinned Nixpkgs at d0e1602ddde669d5beb01aec49d71a51937ed7be)
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
trace: *************************************
trace: * Evaluating device: oneplus-fajita *
trace: *************************************
trace: (Using pinned nur-DataEraserC at d063c0a9cfd5696952e422514e2c357757a517b5)

testing now. 

logs:
Checking that all programs called by relative paths in udev rules exist in /nix/store/s3sh8gi5w7jsvyxnk4k9bh0iqaj457r7-systemd-256.4/lib/udev... OK
Checking that all programs called by absolute paths in udev rules exist... OK
copying path '/nix/store/xvqib1vm7i64qdikjsszh4pa71zj6ryf-libtiff-4.6.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/4j8fci4fhw6p50m7lka7c8yb53x4r44x-lcms2-2.16-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/ifishwy3hkj7bangcj2wrn7k9jw7nyrv-gdk-pixbuf-2.42.12-dev' from 'https://cache.nixos.org'...
building '/nix/store/spn9yhifaq58m5ljyk5xaa7sjf752rjb-cargo-vendor-dir.drv'...
copying path '/nix/store/7d8ygwwm9gyg5wbzwkfs0j0zfffa5p2w-libraw-0.21.2-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/1g1l5r34pb0qrb11l56cai4d31sfm2cc-python3-3.12.4-env' from 'https://cache.nixos.org'...
copying path '/nix/store/4agi53z8j2ji655jnf45vshxflzqv9fi-auto-patchelf-hook' from 'https://cache.nixos.org'...
building '/nix/store/1ndxqx97f3faxrbjavldr1yi3bvfci3j-ttyescape-unstable-2023-03-08.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/my88yq4issfl1p7kh1nl5rfmmv689240-ttyescape-810a195
source root is ttyescape-810a195
Running phase: patchPhase
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
no configure script, doing nothing
Running phase: buildPhase
no Makefile or custom buildPhase, doing nothing
Running phase: installPhase
Running phase: fixupPhase
shrinking RPATHs of ELF executables and libraries in /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08
checking for references to /build/ in /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08...
patching script interpreter paths in /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08
stripping (with command strip and flags -S -p) in  /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/bin
automatically fixing dependencies for ELF files
{'append_rpaths': [],
 'extra_args': [],
 'ignore_missing': [],
 'libs': [PosixPath('/nix/store/4agi53z8j2ji655jnf45vshxflzqv9fi-auto-patchelf-hook/lib'),
          PosixPath('/nix/store/xmd7cjvhrfs1lgddd2w0m4ri7dfhyf7g-binutils-wrapper-2.42/lib'),
          PosixPath('/nix/store/imbw8h46yjayh4zds7a5bl394axhwan5-patchelf-0.15.0/lib'),
          PosixPath('/nix/store/8s80v3snzp2q3p0ldjkh9n2qafjd6c8n-update-autotools-gnu-config-scripts-hook/lib'),
          PosixPath('/nix/store/h9lc1dpi14z7is86ffhl3ld569138595-audit-tmpdir.sh/lib'),
          PosixPath('/nix/store/m54bmrhj6fqz8nds5zcj97w9s9bckc9v-compress-man-pages.sh/lib'),
          PosixPath('/nix/store/wgrbkkaldkrlrni33ccvm3b6vbxzb656-make-symlinks-relative.sh/lib'),
          PosixPath('/nix/store/5yzw0vhkyszf2d179m0qfkgxmp5wjjx4-move-docs.sh/lib'),
          PosixPath('/nix/store/fyaryjvghbkpfnsyw97hb3lyb37s1pd6-move-lib64.sh/lib'),
          PosixPath('/nix/store/kd4xwxjpjxi71jkm6ka0np72if9rm3y0-move-sbin.sh/lib'),
          PosixPath('/nix/store/pag6l61paj1dc9sv15l7bm5c17xn5kyk-move-systemd-user-units.sh/lib'),
          PosixPath('/nix/store/jivxp510zxakaaic7qkrb7v1dd2rdbw9-multiple-outputs.sh/lib'),
          PosixPath('/nix/store/ilaf1w22bxi6jsi45alhmvvdgy4ly3zs-patch-shebangs.sh/lib'),
          PosixPath('/nix/store/cickvswrvann041nqxb0rxilc46svw1n-prune-libtool-files.sh/lib'),
          PosixPath('/nix/store/xyff06pkhki3qy1ls77w10s0v79c9il0-reproducible-builds.sh/lib'),
          PosixPath('/nix/store/aazf105snicrlvyzzbdj85sx4179rpfp-set-source-date-epoch-to-latest.sh/lib'),
          PosixPath('/nix/store/gps9qrh99j7g02840wv5x78ykmz30byp-strip.sh/lib'),
          PosixPath('/nix/store/4agi53z8j2ji655jnf45vshxflzqv9fi-auto-patchelf-hook/lib'),
          PosixPath('/nix/store/xmd7cjvhrfs1lgddd2w0m4ri7dfhyf7g-binutils-wrapper-2.42/lib'),
          PosixPath('/nix/store/imbw8h46yjayh4zds7a5bl394axhwan5-patchelf-0.15.0/lib'),
          PosixPath('/nix/store/8s80v3snzp2q3p0ldjkh9n2qafjd6c8n-update-autotools-gnu-config-scripts-hook/lib'),
          PosixPath('/nix/store/h9lc1dpi14z7is86ffhl3ld569138595-audit-tmpdir.sh/lib'),
          PosixPath('/nix/store/m54bmrhj6fqz8nds5zcj97w9s9bckc9v-compress-man-pages.sh/lib'),
          PosixPath('/nix/store/wgrbkkaldkrlrni33ccvm3b6vbxzb656-make-symlinks-relative.sh/lib'),
          PosixPath('/nix/store/5yzw0vhkyszf2d179m0qfkgxmp5wjjx4-move-docs.sh/lib'),
          PosixPath('/nix/store/fyaryjvghbkpfnsyw97hb3lyb37s1pd6-move-lib64.sh/lib'),
          PosixPath('/nix/store/kd4xwxjpjxi71jkm6ka0np72if9rm3y0-move-sbin.sh/lib'),
          PosixPath('/nix/store/pag6l61paj1dc9sv15l7bm5c17xn5kyk-move-systemd-user-units.sh/lib'),
          PosixPath('/nix/store/jivxp510zxakaaic7qkrb7v1dd2rdbw9-multiple-outputs.sh/lib'),
          PosixPath('/nix/store/ilaf1w22bxi6jsi45alhmvvdgy4ly3zs-patch-shebangs.sh/lib'),
          PosixPath('/nix/store/cickvswrvann041nqxb0rxilc46svw1n-prune-libtool-files.sh/lib'),
          PosixPath('/nix/store/xyff06pkhki3qy1ls77w10s0v79c9il0-reproducible-builds.sh/lib'),
          PosixPath('/nix/store/aazf105snicrlvyzzbdj85sx4179rpfp-set-source-date-epoch-to-latest.sh/lib'),
          PosixPath('/nix/store/gps9qrh99j7g02840wv5x78ykmz30byp-strip.sh/lib')],
 'paths': [PosixPath('/nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08')],
 'recursive': True,
 'runtime_dependencies': []}
auto-patchelf: 0 dependencies could not be satisfied

**Comment by DataEraserC** [comment]
OK, seem like it work fine.

**Comment by gmicroul** [comment]
> OK, seem like it work fine.

[alice@nixos:~]$ uname -asr
Linux nixos 6.4.0 #1-mobile-nixos SMP Tue Jan  1 00:00:00 UTC 1980 aarch64 GNU/Linux

[alice@nixos:~]$ sudo systemctl status hkdm
● hkdm.service - Hotkey Daemon (For) Mobile
     Loaded: loaded (/etc/systemd/system/hkdm.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-07-05 18:03:08 UTC; 8min ago
 Invocation: e241e3a403044ada946c1e121a12cd41
   Main PID: 906 (hkdm)
         IP: 0B in, 0B out
         IO: 796K read, 0B written
      Tasks: 1 (limit: 8028)
     Memory: 1.1M (peak: 2.2M)
        CPU: 53ms
     CGroup: /system.slice/hkdm.service
             └─906 /nix/store/zj3h6ii0rp54hwmwhg49sycdr67xrd2r-hkdm-0.2.1/bin/hkdm -i -c /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/etc/hkdm/config.d/ttyescape>

Jul 05 18:04:14 nixos hkdm[906]: thread '<unnamed>' panicked at src/main.rs:238:33:
Jul 05 18:04:14 nixos hkdm[906]: Failed to run command: /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/bin/togglevt.sh inc
Jul 05 18:04:16 nixos hkdm[906]: thread '<unnamed>' panicked at src/main.rs:238:33:
Jul 05 18:04:16 nixos hkdm[906]: Failed to run command: /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/bin/togglevt.sh inc
Jul 05 18:04:16 nixos hkdm[906]: thread '<unnamed>' panicked at src/main.rs:238:33:
Jul 05 18:04:16 nixos hkdm[906]: Failed to run command: /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/bin/togglevt.sh inc
Jul 05 18:04:17 nixos hkdm[906]: thread '<unnamed>' panicked at src/main.rs:238:33:
Jul 05 18:04:17 nixos hkdm[906]: Failed to run command: /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/bin/togglevt.sh inc
Jul 05 18:04:17 nixos hkdm[906]: thread '<unnamed>' panicked at src/main.rs:238:33:
Jul 05 18:04:17 nixos hkdm[906]: Failed to run command: /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/bin/togglevt.sh reset

[alice@nixos:~]$ 


Service is working but can not boot into tty. just used usb network to check the result.so can not enable keyboard via hkdm.

**Comment by gmicroul** [comment]
[sudo] password for alice: 
● hkdm.service - Hotkey Daemon (For) Mobile
     Loaded: loaded (/etc/systemd/system/hkdm.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-07-05 18:04:05 UTC; 1min 55s ago
 Invocation: b468e754028b46a6b096d958f2421707
   Main PID: 837 (hkdm)
         IP: 0B in, 0B out
         IO: 796K read, 0B written
      Tasks: 1 (limit: 8028)
     Memory: 1.1M (peak: 2.1M)
        CPU: 34ms
     CGroup: /system.slice/hkdm.service
             └─837 /nix/store/zj3h6ii0rp54hwmwhg49sycdr67xrd2r-hkdm-0.2.1/bin/hkdm -i -c /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/etc/hkdm/config.d/ttyescape.toml

Jul 05 18:04:17 nixos hkdm[837]: Failed to run command: /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/bin/togglevt.sh start
Jul 05 18:04:17 nixos hkdm[837]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jul 05 18:04:18 nixos hkdm[837]: thread '<unnamed>' panicked at src/main.rs:238:33:
Jul 05 18:04:18 nixos hkdm[837]: Failed to run command: /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/bin/togglevt.sh inc
Jul 05 18:04:18 nixos hkdm[837]: thread '<unnamed>' panicked at src/main.rs:238:33:
Jul 05 18:04:18 nixos hkdm[837]: Failed to run command: /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/bin/togglevt.sh inc
Jul 05 18:04:19 nixos hkdm[837]: thread '<unnamed>' panicked at src/main.rs:238:33:
Jul 05 18:04:19 nixos hkdm[837]: Failed to run command: /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/bin/togglevt.sh inc
Jul 05 18:04:19 nixos hkdm[837]: thread '<unnamed>' panicked at src/main.rs:238:33:
Jul 05 18:04:19 nixos hkdm[837]: Failed to run command: /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/bin/togglevt.sh reset

[alice@nixos:~]$ sudo systemctl restart hkdm

[alice@nixos:~]$ sudo systemctl status hkdm
● hkdm.service - Hotkey Daemon (For) Mobile
     Loaded: loaded (/etc/systemd/system/hkdm.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-07-05 18:06:08 UTC; 1s ago
 Invocation: abc5791ac4e546439ddb4cf53a89ce64
   Main PID: 899 (hkdm)
         IP: 0B in, 0B out
         IO: 0B read, 0B written
      Tasks: 1 (limit: 8028)
     Memory: 312K (peak: 1.5M)
        CPU: 20ms
     CGroup: /system.slice/hkdm.service
             └─899 /nix/store/zj3h6ii0rp54hwmwhg49sycdr67xrd2r-hkdm-0.2.1/bin/hkdm -i -c /nix/store/mz93n6p8vpaj0b02506gkbks6nj6fj0a-ttyescape-unstable-2023-03-08/etc/hkdm/config.d/ttyescape.toml

Jul 05 18:06:08 nixos systemd[1]: Started Hotkey Daemon (For) Mobile.

[alice@nixos:~]$

**Pull request merged**
